[tool.black]
line_length = 79
target_version = ["py37"]

[tool.poetry]
name = "aiohttp-cache"
version = "2.0.0"
description = "A cache system for aiohttp server"
authors = ["Daniel Garcia (cr0hn) <cr0hn@cr0hn.com>"]
maintainers = [
    "Daniel Garcia (cr0hn) <cr0hn@cr0hn.com>",
    "Artem Zhukov (zhukovgreen) <zhukovgreen@icloud.com",
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Other Audience",
    "License :: OSI Approved :: BSD License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.5",
    "Topic :: Security",
]
readme = "README.md"
repository = "https://github.com/cr0hn/aiohttp-cache"
license = "BSD"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.6"
envparse = "^0.2.0"
aioredis = "^1.3"


[tool.poetry.dev-dependencies]
pytest = "^5.3"
pytest-aiohttp = "^0.3.0"
pytest-cov = "^2.8"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
